# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portless < Formula
  desc "Replace port numbers with stable, named .localhost URLs for local development."
  homepage "https://github.com/acmacalister/portless"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.1/portless_0.1.1_darwin_amd64.tar.gz"
      sha256 "a30a9c7cc2b1e80901f149f0cb9ecf9a8e1a1d43011e6f99053c18c417878bce"

      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.1/portless_0.1.1_darwin_arm64.tar.gz"
      sha256 "d93cc8b308706f9eea9f0433666a3428cd29858f19f744b2ba0b7681963917c5"

      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.1/portless_0.1.1_linux_amd64.tar.gz"
      sha256 "3ef1a829affc6be00d2cb91676e098d4f7f971482c2a89ff9459a9b508cc1555"
      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.1/portless_0.1.1_linux_arm64.tar.gz"
      sha256 "d54504e8d506ad40f68e053da24b035ffdab925f3261cf69e146d52f94c40e89"
      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  test do
    system "#{bin}/portless", "--version"
  end
end
