# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portless < Formula
  desc "Replace port numbers with stable, named .localhost URLs for local development."
  homepage "https://github.com/acmacalister/portless"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.0/portless_0.1.0_darwin_amd64.tar.gz"
      sha256 "c539d1d765bfe58b77c73d72623b05f477090d060c2ed59fb98da08f74bf75fd"

      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.0/portless_0.1.0_darwin_arm64.tar.gz"
      sha256 "de26ac38716e8e6367142be48cef2c299fa0be28e7beb34dc464bb861daf10a7"

      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.0/portless_0.1.0_linux_amd64.tar.gz"
      sha256 "912b855cd3863e02e892537a79e312dd19de3640616f9970800f69633d764b1a"
      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.1.0/portless_0.1.0_linux_arm64.tar.gz"
      sha256 "33ac9997ea75da3385ae5397e4b654b858af6311cd8afc5d2875eede7cbb0509"
      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  test do
    system "#{bin}/portless", "--version"
  end
end
