# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portless < Formula
  desc "Replace port numbers with stable, named .localhost URLs for local development."
  homepage "https://github.com/acmacalister/portless"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acmacalister/portless/releases/download/v0.2.0/portless_0.2.0_darwin_amd64.tar.gz"
      sha256 "e631b761a03fb292d680f1b5d5a530972338b2a8674d6976c690f43c121ea872"

      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acmacalister/portless/releases/download/v0.2.0/portless_0.2.0_darwin_arm64.tar.gz"
      sha256 "ce5d3e071d3bf64412ecfa211920c101f819f1b0e3f6cb163f26f25f764df290"

      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.2.0/portless_0.2.0_linux_amd64.tar.gz"
      sha256 "9bff6ac04cd3fabe16174fd98e853293e9f00a5ef4dd055be09adb2eb2187dba"
      define_method(:install) do
        bin.install "portless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acmacalister/portless/releases/download/v0.2.0/portless_0.2.0_linux_arm64.tar.gz"
      sha256 "ddcd1a432b872e9a6a88f57a4b6fd7001ba6e2e57d87924de05e67ccfe386207"
      define_method(:install) do
        bin.install "portless"
      end
    end
  end

  test do
    system "#{bin}/portless", "--version"
  end
end
